name: workshop-dl

on:
  workflow_dispatch:

jobs:
  setup-and-download-entry:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install steamcmd
        run: |
          sudo add-apt-repository -y multiverse
          sudo dpkg --add-architecture i386
          echo steam steam/question select "I AGREE" | sudo debconf-set-selections
          echo steam steam/license note "" | sudo debconf-set-selections
          sudo apt update
          sudo apt install -y steamcmd

      - name: Run steamcmd
        run: |
          sudo chmod +x ./input.sh
          source ./input.sh
          exec steamcmd +login anonymous +workshop_download_item $APP_ID $ENTRY_ID +quit

      - name: Move contents
        run: |
          cp -r /home/runner/Steam/steamapps/workshop/content/$APP_ID/$ENTRY_ID ./downloaded/
          ls -lar ./downloaded/
        shell: bash

      - name: Save contents to repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Add downloaded workshop item $ENTRY_ID"
          git push
        shell: bash
